### ISSUE TITLE
第1章【绪论】（固定习题）

### ISSUE THREAD

**Issue by LLZcoder** [dreamCirno/Princlples-of-Accounts#1]
雨课堂第27题，选项有5个，A年度，B半年度，C季度，D月度，E旬

**Comment by LLZcoder** [comment]
课本14题，正确选项是 C、D

**Comment by LLZcoder** [comment]
课本第15题，四个选项内容错误

**Comment by LLZcoder** [comment]
雨课堂第三题，下列属于流动负债的是，A预收账款

**Comment by LLZcoder** [comment]
雨课堂在26题之后，漏了1题，“持续经营假设是假设企业可以长生不老，即使进入破产清算，也不应该改变会计核算方法，  ×  ”

**Comment by LLZcoder** [comment]
课本第15题之后漏了1题，”会计核算所产生的信息，应具有（）“，A合理性，B完整性，C连续性，D系统性

**Comment by dreamCirno** [comment]
感谢反馈！最近在准备安卓答辩，待答辩结束后立马更新。

**Comment by dreamCirno** [comment]
已修复，如有问题，请在 Issues 提出
